@startuml
actor User
participant WebPage
participant FlaskApp
participant Database
collections KerasModel

group Add training measurement
autonumber
User -> WebPage: Training Measurement
WebPage -> WebPage: Validation
WebPage -> FlaskApp: JSON
FlaskApp -> FlaskApp: Formatting
FlaskApp -> Database: Formatted measurement
FlaskApp --> WebPage: MeasurementId
WebPage --> User: Message
end

group Predict result
autonumber
User -> WebPage: Measurement
WebPage -> WebPage: Validation
WebPage -> FlaskApp: JSON
FlaskApp -> FlaskApp: Formatting
FlaskApp -> Database: Formatted measurement
FlaskApp -->WebPage: MeasurementId
WebPage -> FlaskApp: Get result page
FlaskApp --> WebPage: Redirect
FlaskApp -> Database: Get measurement for prediction
Database --> FlaskApp: Measurement
FlaskApp -> KerasModel: Predict
KerasModel --> FlaskApp: Prediction
WebPage -> FlaskApp: Get result (async)
FlaskApp --> WebPage: Result
WebPage -> User: Show result
end

group Retrain model
autonumber
User -> FlaskApp: API Call /retrain
FlaskApp -> Database: Get training data
Database --> FlaskApp: Training data
FlaskApp -> KerasModel: Retrain based on all measurements
KerasModel --> FlaskApp
FlaskApp --> User
end

@enduml